# Generated by Django 3.2.16 on 2022-12-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Guest First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Guest Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adress')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact Phone')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='House Name')),
                ('adress', models.CharField(max_length=30, verbose_name='House Adress')),
                ('owner', models.CharField(max_length=30, verbose_name='House Owner')),
                ('description', models.TextField(blank=True)),
                ('booking', models.ManyToManyField(blank=True, to='beachhouse.Guests')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(verbose_name='Check In')),
                ('checkout', models.DateTimeField(verbose_name='Check Out')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachhouse.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
