# Generated by Django 3.2.16 on 2022-12-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0002_auto_20221219_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='Guest First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Guest Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adress')),
                ('phone', models.CharField(max_length=15, verbose_name='Contact Phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='booking',
        ),
        migrations.AddField(
            model_name='house',
            name='beds',
            field=models.IntegerField(default=0, verbose_name='Number Of Beds'),
        ),
        migrations.AddField(
            model_name='house',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Number Of Guets'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhouse.house'),
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhouse.guests'),
        ),
    ]
