# Generated by Django 3.2.16 on 2022-12-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0003_auto_20221221_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beachhouse.owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fname',
            field=models.CharField(max_length=20, verbose_name='Owner First Name'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lname',
            field=models.CharField(max_length=20, verbose_name='Owner Last Name'),
        ),
    ]
