# Generated by Django 3.2.16 on 2022-12-30 15:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0006_alter_house_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
