# Generated by Django 3.2.16 on 2023-01-08 10:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0009_auto_20230108_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)]),
        ),
    ]
