# Generated by Django 3.2.16 on 2023-01-08 10:26

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0010_auto_20230108_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 8, 10, 26, 45, 806413, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 8, 10, 26, 45, 806445, tzinfo=utc))]),
        ),
    ]
