# Generated by Django 3.2.16 on 2023-01-22 11:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0015_auto_20230117_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bed_size',
            field=models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('Q', 'Queen'), ('K', 'King')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='house',
            name='has_bath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_bbq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 22, 11, 40, 35, 555904, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 22, 11, 40, 35, 555935, tzinfo=utc))]),
        ),
    ]
