# Generated by Django 3.2.16 on 2023-01-29 17:39

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0017_auto_20230126_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, verbose_name='First Name')),
                ('lname', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adress')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('message', models.CharField(max_length=300, verbose_name='Message')),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 29, 17, 39, 23, 528860, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 1, 29, 17, 39, 23, 528902, tzinfo=utc))]),
        ),
    ]
