# Generated by Django 3.2.16 on 2023-02-05 18:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('beachhouse', '0019_auto_20230131_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='checkin',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 5, 18, 40, 24, 545173, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checkout',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 2, 5, 18, 40, 24, 545202, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
    ]
